"""fix discrepancies

A bunch of minor fixes. We got away with these flaws so far but it will bug me
if I don't do something about them

Revision ID: f49ff9c35283
Revises: d965a0d5f9ef
Create Date: 2025-02-13 12:28:07.067057

"""

from collections.abc import Sequence

import sqlalchemy as sa
from parrot.db import GuildMeta

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f49ff9c35283"
down_revision: str | None = "d965a0d5f9ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	# Correct the name of this constraint to contain the entire composite key
	with op.batch_alter_table("antiavatar") as bop:
		bop.drop_constraint(op.f("pk_antiavatar_user_id"), type_="primary")
		bop.create_primary_key(
			op.f("pk_antiavatar_guild_id_user_id"), ["guild_id", "user_id"]
		)

	with op.batch_alter_table("channel") as bop:
		# IDs autogenerated from SQLAlchemy were typed as Integer, but we know
		# that they are going to be 64-bit numbers, so it would be better to
		# type them more specifically as BigInts.
		bop.alter_column(
			"id", existing_type=sa.Integer(), type_=sa.BigInteger()
		)
		bop.alter_column(
			"webhook_id", existing_type=sa.Integer(), type_=sa.BigInteger()
		)
		# Make these columns use the dialect's built-in Boolean type, if it has
		# one.
		for name in ("can_speak_here", "can_learn_here"):
			bop.alter_column(
				name,
				existing_type=sa.Integer(),
				type_=sa.Boolean(),
				existing_nullable=False,
				server_default=sa.false(),
			)

	with op.batch_alter_table("guild") as bop:
		bop.alter_column(
			"id", existing_type=sa.Integer(), type_=sa.BigInteger()
		)
		# Ensure these defaults are quoted in the database, because they can be
		# empty and intentionally have trailing spaces.
		bop.alter_column(
			"imitation_prefix",
			server_default=f"'{GuildMeta.default_imitation_prefix}'",
		)
		bop.alter_column(
			"imitation_suffix",
			server_default=f"'{GuildMeta.default_imitation_suffix}'",
		)
		# 64-bit Snowflake timestamp; type as BigInt
		# It was also missing its NULL default
		bop.alter_column(
			"gone_since",
			existing_type=sa.Integer(),
			type_=sa.BigInteger(),
			existing_nullable=True,
			server_default=sa.null(),
		)

	with op.batch_alter_table("membership") as bop:
		bop.alter_column(
			"guild_id", existing_type=sa.Integer(), type_=sa.BigInteger()
		)
		bop.alter_column(
			"user_id", existing_type=sa.Integer(), type_=sa.BigInteger()
		)
		# Rename to include entire composite key
		# SQLAlchemy headache #14: this one is "primary" and not "primarykey"
		bop.drop_constraint(op.f("pk_membership_user_id"), type_="primary")
		bop.create_primary_key(
			op.f("pk_membership_guild_id_user_id"),
			columns=["guild_id", "user_id"],
		)

		bop.alter_column(
			"ended_since",
			existing_type=sa.Integer(),
			type_=sa.BigInteger(),
			existing_nullable=True,
			server_default=sa.null(),
		)
		# Was missing default false
		bop.alter_column("is_registered", server_default=sa.false())

	with op.batch_alter_table("message") as bop:
		bop.alter_column(
			"id", existing_type=sa.Integer(), type_=sa.BigInteger()
		)
		bop.alter_column(
			"author_id",
			existing_type=sa.Integer(),
			type_=sa.BigInteger(),
			existing_nullable=False,
		)
		# Drop a redundant foreign key constraint that might cause problems;
		# foreign key to membership on (guild_id+author_id) should be used
		# instead.
		bop.drop_constraint(
			op.f("fk_message_guild_id_guild"), type_="foreignkey"
		)

	with op.batch_alter_table("user") as bop:
		bop.alter_column(
			"id", existing_type=sa.Integer(), type_=sa.BigInteger()
		)
		# Was the string "1" before 🤷
		bop.alter_column("wants_random_wawa", server_default=sa.true())


def downgrade() -> None:
	pass
